### ISSUE TITLE
Documentation of handler pipeline

### ISSUE THREAD

**Issue by arafalov** [attoparser/attoparser#12]
I like the project, but I found it quite difficult to put together the - few - lines needed to make a simple test work. I wanted to find all elements of particular type and print out the element's attributes with the source location. I feel that particular use cases is one of the things other parsers make very hard to do.

The quick hack result is at: https://gist.github.com/arafalov/85ec492ecc1a08139d7b188af94ddb66 . I would be very happy if it were useful somehow and you can use it freely with or without attribution.

**Comment by danielfernandez** [comment]
Thanks a lot @arafalov. Unfortunately AttoParser 2.0 was published in a real rush to make Thymeleaf 3.0 *hit the shelves* (it was conceived as the new Thymeleaf parser, though it is of course useful in a huge amount of other scenarios). So I still have to update the docs. Actually, to re-write them almost completely for 2.0. But that's still in the TO-DO, and the Thymeleaf 3 release doc hasn't been completed yet :(

As for your code, it looks nice to me. Unfortunately your need to output the `line` and `col` for each `<filter>` forces you to not use a mere `OutputMarkupHandler` instead of your `new SimplifierMarkupHandler(new ElementHandler())` (and then have your code reduced to only four lines of code).

For testing purposes, I would also recommend you to explore the `TraceBuilderMarkupHandler`, which will build a `List<MarkupTraceEvent>` for you from the events it receives (for example, for the ones already matched by the `filter` selection expression). 

These *event objects* contain the `line` and `col` info, and represent a very handy format for moving around information about where and how specific events happen during parsing. This is actually the most common mechanism that is used for testing AttoParser itself, by defining the exact trace that should be output by a parsing operation –in a `String`– and comparing it with the result of serializing as `String` the trace events output by a `TraceBuilderMarkupHandler` handler. See an example: https://github.com/attoparser/attoparser/blob/master/src/test/java/org/attoparser/MarkupParserTest.java#L120-L123
